
name: Build and test

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt-get install liblapack-dev gfortran libboost-dev hwloc

      - name: Cache build dependencies
        uses: actions/cache@master
        env:
          cache-name: cache-built-dependencies
        with:
          path: |
            dependencies/include
            dependencies/lib
          key: ${{ runner.os }}-build

      - name: CMake configuration
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE ..
      - name: Build using make
        run: cd build && make -j
      - name: Hierarchical LU execution test
        run: ./bin/h_lu 256 32 8 2 1
